name: Deploy DEPLOY Branch

on:
  push:
    branches: [ "deploy" ]
  # schedule:
  #   # Phút / Giờ / Ngày / Tháng / Thứ trong tuần
  #   - cron: '0 20 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Nạp biến môi trường để nhận diện npm/node
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            cd /home/project/social-learning || exit
            
            # 1. Cập nhật code
            git fetch --all
            git reset --hard origin/deploy
            
            # 2. Server
            cd server
            npm install
            pm2 restart server || pm2 start npm --name "server" -- run start
            cd ..

            # 3. Web
            cd web
            npm install
            npm run build
            pm2 restart webapp || pm2 start npm --name "webapp" -- run start